#!/usr/bin/env bash
#
# github-org-wizard:创建 GitHub 组织(合集模式迁移第一步)
# 一步步带你建组织、校验权限,并把组织名写进 ~/.config/automation-suite/org.env。
# 用法:bash scripts/github-org-wizard.sh
# 组织只能由人在网页上创建 —— 这个脚本负责指路、校验与记录,不代建。
#
# 注:用户后来放弃了「按仓库合集迁到组织」的方案,改成单仓库 + 每项目一个文件夹,
# 本脚本与 transfer-repos.sh 保留作历史参考,平时不需要跑。
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi
# RED 在这两个向导里没有用到,保留以与其它向导的库保持一致
: "$RED"

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

# 值持久化到 ~/.config/automation-suite/org.env(不是仓库内的 .env)
ENV_FILE="$HOME/.config/automation-suite/org.env"
mkdir -p "$(dirname "$ENV_FILE")"

banner "GitHub 组织创建(合集模式迁移第一步)"

# ── Stage 1: 在网页上创建组织 ─────────────────────────────────────────────
stage "创建组织(只能在网页做)"
say "GitHub 没有创建组织的 API,网页是唯一入口;这一步只能你来点。"
say "建好之后 github.com/<组织名> 本身就是合集页,取代现在靠 zzz-automation topic 拼出来的列表。"
open_url "https://github.com/settings/organizations"
step "点页面上的 New organization(直达链接:https://github.com/account/organizations/new)。"
step "计划选 Free:私有仓库无限、Actions 2,000 分钟/月,与现在的个人 Free 完全一致,不产生费用。"
step "组织名自己定,建议延续 zzz 前缀(例如 zzz-automation);显示名可以随便填。"
step "Owner 选你自己的账号,邮箱与验证按页面提示走。"
warn "组织名是全局唯一的,而且建后改名会让下面所有仓库的 URL 再变一次 —— 有仓库转进去之后就别再改名。"
pause "组织建好、能打开 github.com/<组织名> 页面后按回车继续"

# ── Stage 2: 校验组织与权限 ───────────────────────────────────────────────
stage "校验组织与权限"
say "用 gh 确认组织存在,并且你的账号有在它下面建仓库的权限(仓库转移的前提)。"
ask ORG_NAME "输入刚建的组织名(不是显示名):"
ORG_NAME="${ORG_NAME:-}"
if [[ -z "$ORG_NAME" ]]; then
  warn "没填组织名,跳过校验;重跑本脚本可以补上。"
elif ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
  warn "gh 不可用或未登录;先跑 gh auth login 再重跑本脚本。"
else
  if login=$(gh api "orgs/$ORG_NAME" --jq '.login' 2>/dev/null); then
    printf '  %s✓%s 组织存在:%s\n' "$GREEN" "$RESET" "$login"
  else
    warn "读不到组织 $ORG_NAME:确认名字拼写正确、且你的账号是它的 owner。"
  fi
  # shellcheck disable=SC2016  # GraphQL 的 $o 由 gh 传给服务端,不能由 shell 展开
  ORG_QUERY='query($o:String!){organization(login:$o){viewerCanCreateRepositories viewerIsAMember viewerCanAdminister}}'
  perms=$(gh api graphql -f query="$ORG_QUERY" -f o="$ORG_NAME" \
    --jq '.data.organization|"create=\(.viewerCanCreateRepositories) member=\(.viewerIsAMember) admin=\(.viewerCanAdminister)"' 2>/dev/null || echo "")
  if [[ "$perms" == create=true* ]]; then
    printf '  %s✓%s 有建仓库权限(%s)\n' "$GREEN" "$RESET" "$perms"
  elif [[ -n "$perms" ]]; then
    warn "权限看起来不够($perms);转移会失败,先在组织里把自己设为 owner。"
  else
    warn "权限查询失败;若 gh 看不到组织下的仓库,去组织 Settings -> Third-party Access 放开 OAuth App,或 gh auth refresh -s read:org,repo"
  fi
fi
pause "看完校验结果后按回车继续"

# ── Stage 3: 写入组织名并交接 ─────────────────────────────────────────────
stage "记录组织名,交接给转移脚本"
say "组织名写进 $ENV_FILE,下一步的转移脚本从这里读。"
ORG_NAME="${ORG_NAME:-}"
if [[ -n "$ORG_NAME" ]]; then
  write_env ORG_NAME "$ORG_NAME"
  write_env ORG_CREATED_AT "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
else
  warn "组织名是空的,没有写入;重跑本脚本或手工写 ORG_NAME=... 到 $ENV_FILE"
fi
say "接下来由助手/脚本完成仓库转移,计划转这三个(都不是 fork):"
note "automation-suite · weread-signin · home-automation-configs"
note "转移脚本:bash scripts/transfer-repos.sh(默认 dry-run,确认后加 --apply)"
note "Zzz210s/weread-bot 不在转移范围:它是 fork,且带着开放中的上游 PR #53。"
pause "按回车继续"

# ── Stage 4: 关闭前的叮嘱 ─────────────────────────────────────────────────
stage "在转移确认完成前,不要手动移动仓库"
warn "现在什么都别做:不要在网页上 Transfer,不要在旧位置新建同名仓库。"
step "手动转移会绕开脚本的记录与复核,而且旧位置一旦被重新建仓,原地址的跳转会被永久删除。"
step "等 transfer-repos.sh 跑完并复核通过,再按需要改文档链接。"
step "回滚很简单:组织 owner 可以把仓库再转回 Zzz210s,一条 gh api 命令。"
pause "看完按回车结束"
