#!/usr/bin/env bash
#
# public-reset-wizard:删库重建 + 更名 home-automation-configs -> scripts-hub。
#
# 为什么要删库:本仓库 force push 清洗过历史,旧对象仍能按旧 SHA 取到 —— 只有
# 删库重建才真正消失。本轮顺带更名:删掉 Zzz210s/home-automation-configs,
# 以新名 Zzz210s/scripts-hub 重建为 PUBLIC(旧对象随旧库一起消失),再把本地
# 干净历史推过去、origin 改指新地址。
# 本地目录名沿用 home-automation-configs(只改远程仓库名,免得带偏本机计划任务)。
# 备份镜像:优先新名 scripts-hub-backup-*.git,同时接受更名前的旧名
# home-automation-configs-backup-*.git —— 两种名字都算合格备份。
# weread-signin 已并入本仓库的 weread-signin/ 快照,不再有独立仓库要处理。
#
# 不重领微信读书 API Key:Key 片段进过 git 历史,但仓库当时是私有的、旧 SHA 从未公开,
# 用户判断不必轮换。本向导只读取现有 Key,推送后用它跑一次只读校验。
#
# 用法:bash scripts/public-reset-wizard.sh
# 机器相关路径不写死:默认读 ~/.config/automation-suite/local-paths.env,也可用环境变量覆盖。
# 可随时 Ctrl-C;重跑会跳过已完成的部分(已删的仓库、已建的仓库、已推送的历史)。
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# ── 目标与本地路径(默认读机器私有文件,环境变量优先) ──────────────────
LOCAL_PATHS_FILE="${AUTOMATION_LOCAL_PATHS:-$HOME/.config/automation-suite/local-paths.env}"
# shellcheck source=/dev/null
[[ -f "$LOCAL_PATHS_FILE" ]] && . "$LOCAL_PATHS_FILE"

OWNER="${OWNER:-Zzz210s}"
OLD_SLUG="$OWNER/home-automation-configs"   # 待删除的旧名仓库
NEW_SLUG="$OWNER/scripts-hub"               # 重建后的新名仓库
WEREAD_DIR="${WEREAD_SIGNIN_DIR:-$HOME/weread-signin}"
HAC_DIR="${HOME_AUTOMATION_CONFIGS_DIR:-$HOME/home-automation-configs}"  # 本地目录名不改
# 备份镜像:新名优先(scripts-hub),旧名兼容(home-automation-configs)。
HAC_BACKUP_GLOB="${HAC_BACKUP_GLOB:-$HOME/scripts-hub-backup-*.git}"
HAC_BACKUP_OLD_GLOB="${HAC_BACKUP_OLD_GLOB:-$HOME/home-automation-configs-backup-*.git}"
HAC_BACKUP_GLOBS=("$HAC_BACKUP_GLOB" "$HAC_BACKUP_OLD_GLOB")
KEY_FILE="${WEREAD_API_KEY_FILE:-$WEREAD_DIR/secrets/weread-api-key.txt}"
SHA_DIR="${TMPDIR:-/tmp}/public-reset-old-shas"
SHA_FILE="$SHA_DIR/home-automation-configs.txt"          # 删除前记下的旧 SHA
TOPIC_FILE="$SHA_DIR/home-automation-configs-topics.txt" # 删除前抄下的旧 topics

# 本向导不写 .env:把库的 ENV_FILE 指到临时文件,免得误读工作目录里已有的 .env。
ENV_FILE="${TMPDIR:-/tmp}/public-reset-wizard.env"

# 新名仓库的一句英文简介:三个自动化程序的脚本、配置与文档汇总。
HAC_DESC="Runner scripts, configuration, and documentation for three Windows automation programs: Microsoft Rewards, WeRead check-in, and Zhihuishu course playback."
# topics 优先从旧仓库现读(改名后原样沿用);读不到时退回这份 2026-10-04 的清单。
# GitHub 不接受点号:topic 只能是小写字母数字与连字符。
HAC_TOPICS=(automation configuration docs microsoft-rewards operations playwright self-hosted wecom windows-task-scheduler weread windows zzz-automation autovisor backup-restore oracle-cloud systemd gplv3)

# 个人标识黑名单:默认只查通用 Key 形状;本机私有文件里一行一个额外模式,
# 真实姓名/邮箱/旧 handle 这些**绝不写进仓库**(文件默认在 ~/.config/automation-suite/ 下)。
SENSITIVE_PATTERN='wrk-[A-Za-z0-9_-]{12}'
SENSITIVE_FILE="${SENSITIVE_PATTERNS_FILE:-$HOME/.config/automation-suite/sensitive-patterns.txt}"
if [[ -f "$SENSITIVE_FILE" ]]; then
  while IFS= read -r _p; do
    [[ -n "$_p" ]] && SENSITIVE_PATTERN="$SENSITIVE_PATTERN|$_p"
  done < "$SENSITIVE_FILE"
fi

wsh_ok()   { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }
wsh_bad()  { printf '  %s✗%s %s\n' "$RED" "$RESET" "$1"; }
wsh_die()  { printf '\n%s[停止]%s %s\n' "$RED" "$RESET" "$1" >&2; shift || true
             for l in "$@"; do printf '       %s\n' "$l" >&2; done; exit 1; }

# find_backups <glob>...:列出匹配的备份镜像目录,最新的排最前。
find_backups() {
  local pattern m i
  local -a found=() out=()
  for pattern in "$@"; do
    while IFS= read -r m; do found+=("$m"); done < <(compgen -G "$pattern" || true)
  done
  for m in "${found[@]}"; do
    i=${#out[@]}
    while (( i > 0 )) && [[ "$m" -nt "${out[i-1]}" ]]; do i=$((i - 1)); done
    out=("${out[@]:0:i}" "$m" "${out[@]:i}")
  done
  (( ${#out[@]} )) && printf '%s\n' "${out[@]}"
  return 0
}

# check_backup <label> <varname> <glob>...:备份必须存在且是可读、有提交的 git 仓库。
# 可传多个候选模式(新名在前、旧名在后),取最新的一份。
check_backup() {
  local label="$1" varname="$2" count dir
  shift 2
  local -a matches=()
  while IFS= read -r m; do matches+=("$m"); done < <(find_backups "$@")
  (( ${#matches[@]} )) || wsh_die "找不到 $label 的备份(已试模式:$*)。" \
    "重建前必须有镜像备份,否则拒绝继续 —— 一条命令都不会执行。" \
    "先做一份:git clone --mirror <仓库URL> <路径>.git"
  dir="${matches[0]}"
  [[ -d "$dir" ]] || wsh_die "$label 的备份路径不是目录:$dir" "删库前先修好备份。"
  count=$(git --git-dir="$dir" rev-list --count --all 2>/dev/null) \
    || wsh_die "$label 的备份不是可读的 git 仓库:$dir" "删库前先修好备份。"
  (( count > 0 )) || wsh_die "$label 的备份里没有提交:$dir" "删库前先修好备份。"
  printf -v "$varname" '%s' "$dir"
  wsh_ok "$label 备份可用:$dir($count 个提交)"
}

# gh_has_scope <scope>:从 x-oauth-scopes 响应头判断当前 token 的权限范围。
gh_has_scope() {
  local scopes
  scopes=$(gh api -i user 2>/dev/null | tr -d '\r' \
    | awk -F': ' 'tolower($1)=="x-oauth-scopes"{print $2}') || return 1
  [[ ",${scopes// /}," == *",$1,"* ]]
}

# capture_old_shas:删库前记录一批"重写前的旧 SHA",删完用来验证旧对象真的取不回。
# 两个来源:线上现有 ref(force push 后仍能取回的那些)+ 备份里重写前的提交(抽样 5 个)。
capture_old_shas() {
  local file="$SHA_FILE"
  mkdir -p "$SHA_DIR"
  : > "$file"
  git ls-remote "https://github.com/$OLD_SLUG.git" 2>/dev/null \
    | awk '{print $1}' >> "$file" || true
  # 新名与旧名镜像都算,每个抽 5 个提交(重写前的旧对象在旧名镜像里)
  local m
  while IFS= read -r m; do
    git --git-dir="$m" rev-list --all 2>/dev/null | head -n 5 >> "$file" || true
  done < <(find_backups "${HAC_BACKUP_GLOBS[@]}")
  sort -u -o "$file" "$file"
  note "$OLD_SLUG 记下 $(grep -c . "$file" || true) 个旧 SHA(线上 ref + 备份里的旧提交)"
}

# capture_topics:删库前把旧仓库的 topics 抄下来,重建后原样写到新仓库。
# 读不到(没网/权限不足)就用 HAC_TOPICS 备份清单;抄下来的顺手按 GitHub 规则清洗。
capture_topics() {
  mkdir -p "$SHA_DIR"
  if gh api "repos/$OLD_SLUG/topics" --jq '.names[]' > "$TOPIC_FILE" 2>/dev/null \
     && [[ -s "$TOPIC_FILE" ]]; then
    grep -E '^[a-z0-9][a-z0-9-]*$' "$TOPIC_FILE" > "$TOPIC_FILE.clean" || true
    mv "$TOPIC_FILE.clean" "$TOPIC_FILE"
    note "$OLD_SLUG 现读 topics $(grep -c . "$TOPIC_FILE" || true) 个,重建后照抄"
  else
    printf '%s\n' "${HAC_TOPICS[@]}" > "$TOPIC_FILE"
    warn "读不到旧仓库 topics,改用本地备份清单(${#HAC_TOPICS[@]} 个)"
  fi
}

# load_topics:把抄下来的 topics 读进 HAC_TOPICS(替换静态清单);文件为空则保留静态清单。
load_topics() {
  local -a t=()
  while IFS= read -r _t; do [[ -n "$_t" ]] && t+=("$_t"); done < "$TOPIC_FILE"
  (( ${#t[@]} )) && HAC_TOPICS=("${t[@]}")
  return 0
}

delete_repo() {
  local slug="$1" backup="$2" verify
  if ! gh api "repos/$slug" --jq .full_name >/dev/null 2>&1; then
    wsh_ok "$slug 已经不存在,跳过删除"
    return 0
  fi
  verify=$(git --git-dir="$backup" rev-list --count --all 2>/dev/null || echo 0)
  (( verify > 0 )) || wsh_die "备份 $backup 读不出提交,拒绝删除 $slug。" "先修好备份再重跑。"
  if ! confirm "确认删除远程 $slug?(回滚只能靠备份 $backup 的 $verify 个提交)"; then
    wsh_die "已取消,什么都没删。" \
      "想走网页删:$OLD_SLUG 的 Settings -> Danger Zone" \
      "删完重跑本脚本,它会跳过删除直接重建。"
  fi
  gh repo delete "$slug" --yes || wsh_die "删除 $slug 失败。" \
    "常见原因:token 缺 delete_repo 权限(回上一阶段授权)。" \
    "也可以去 https://github.com/$slug/settings 的 Danger Zone 手动删,再重跑本脚本。"
  if gh api "repos/$slug" --jq .full_name >/dev/null 2>&1; then
    wsh_die "$slug 删除命令返回成功,但仓库仍然存在。" \
      "去 https://github.com/$slug/settings 手动确认,再重跑。"
  fi
  wsh_ok "$slug 已删除"
}

create_repo() {
  local slug="$1" desc="$2"
  if gh api "repos/$slug" --jq .full_name >/dev/null 2>&1; then
    warn "$slug 已存在,跳过创建(确认它就是重建出来的空库,才继续下一步)"
    return 0
  fi
  gh repo create "$slug" --public --description "$desc" \
    || wsh_die "创建 $slug 失败。" \
         "若提示名字冲突:删库可能还没生效,等几秒重跑。" \
         "也可以去 https://github.com/new 手动建一个空的 PUBLIC 仓库,再重跑本脚本。"
  wsh_ok "已创建 $slug(PUBLIC)"
}

set_topics() {
  local slug="$1"; shift
  local json='{"names":[' first=1 t
  for t in "$@"; do
    (( first )) || json+=','
    json+="\"$t\""; first=0
  done
  json+=']}'
  if printf '%s' "$json" | gh api -X PUT "repos/$slug/topics" --input - >/dev/null 2>&1; then
    wsh_ok "$slug:topics 已设置($# 个)"
  else
    warn "$slug:topics 设置失败,稍后手动补"
    SKIPPED+=("$slug topics")
  fi
}

# check_no_old_objects <slug> <dir>:重写前的旧 SHA 必须在远程已取不回。
# 用一次性裸库去试,免得把旧对象又取回本地克隆。
check_no_old_objects() {
  local slug="$1" dir="$2" file="${3:-$SHA_FILE}" sha type bad=0 total=0
  local probe
  [[ -f "$file" ]] || { note "$slug:没有记录删除前的 SHA,跳过旧对象检查"; return 0; }
  probe="$(mktemp -d)/probe.git"
  git init --bare --quiet "$probe"
  while read -r sha; do
    [[ -n "$sha" ]] || continue
    if git -C "$dir" merge-base --is-ancestor "$sha" main 2>/dev/null; then continue; fi
    total=$(( total + 1 ))
    if git --git-dir="$probe" fetch --quiet --no-tags "https://github.com/$slug.git" "$sha" 2>/dev/null; then
      type=$(git --git-dir="$probe" cat-file -t "$sha" 2>/dev/null || echo unknown)
      if [[ "$type" == "commit" ]]; then
        wsh_bad "旧提交仍可取回:$sha"
        bad=$(( bad + 1 ))
      fi
    fi
  done < "$file"
  rm -rf "$(dirname "$probe")"
  if (( bad )); then
    warn "有 $bad 个重写前的提交还能按旧 SHA 取到:远程仍留着旧对象,查一下删的是不是同一个仓库"
  else
    wsh_ok "重写前的 $total 个提交都已取不到(旧历史确实没了)"
  fi
  return 0
}

publish_repo() {
  local slug="$1" dir="$2" dirty local_sha remote_sha emails hits
  [[ -d "$dir/.git" ]] || wsh_die "找不到本地仓库:$dir" "先克隆出清洗后的历史再重跑。"
  dirty=$(git -C "$dir" status --porcelain)
  [[ -z "$dirty" ]] || wsh_die "$dir 有未提交改动,先处理干净再推。" "$dirty"
  git -C "$dir" remote set-url origin "https://github.com/$slug.git"
  git -C "$dir" push -u origin main \
    || wsh_die "$slug 推送失败。" "确认仓库已重建、且是空库(有内容会拒推)。"
  git -C "$dir" fetch --quiet origin main
  local_sha=$(git -C "$dir" rev-parse main)
  remote_sha=$(git -C "$dir" rev-parse origin/main)
  if [[ "$local_sha" == "$remote_sha" ]]; then
    wsh_ok "$slug main 已同步:$local_sha"
  else
    wsh_bad "$slug 本地与远程 main 不一致($local_sha / $remote_sha)"
  fi
  wsh_ok "$slug 提交 $(git -C "$dir" rev-list --count main) 个 · 入库文件 $(git -C "$dir" ls-files | wc -l) 个"
  emails=$(git -C "$dir" log --format='%ae' | sort -u)
  if [[ "$emails" == "zzz210s@qq.com" ]]; then
    wsh_ok "$slug 作者邮箱只剩 zzz210s@qq.com"
  else
    wsh_bad "$slug 作者邮箱还有:$emails"
  fi
  hits=$(git -C "$dir" ls-files \
    | grep -E '(^|/)(secrets?|credentials?)(/|$)|(^|/)\.env$|webhook|api-key|\.cookie$' || true)
  if [[ -z "$hits" ]]; then
    wsh_ok "$slug 入库文件里没有凭据类路径"
  else
    wsh_bad "$slug 入库文件疑似含凭据:$(printf '%s' "$hits" | tr '\n' ' ')"
  fi
  hits=$(git -C "$dir" grep -I -n -E "$SENSITIVE_PATTERN" main || true)
  if [[ -z "$hits" ]]; then
    wsh_ok "$slug 内容里没有真实 Key 与个人标识"
  else
    warn "$slug 内容里还有可疑字符串(自查后再决定是否改):"
    printf '%s\n' "$hits" | head -n 5 | while read -r l; do note "  $l"; done
  fi
  wsh_ok "$slug 可见性 $(gh api "repos/$slug" --jq .visibility) · 许可 $(gh api "repos/$slug" --jq '.license.spdx_id // "未识别"')"
}

# prune_local <dir>:重写前的旧对象还留在本地 pack 里当垃圾 —— 它们不会被 push,
# 但以后 git push --mirror / 打包时容易漏出去。推之前先剪掉,让本地与公开的版本对齐。
prune_local() {
  local dir="$1" before after
  before=$(git -C "$dir" count-objects -v | awk '/^size-pack/{print $2}')
  git -C "$dir" reflog expire --expire=now --all
  git -C "$dir" gc --prune=now --quiet
  after=$(git -C "$dir" count-objects -v | awk '/^size-pack/{print $2}')
  wsh_ok "$dir 已剪掉不可达对象(pack ${before}KiB -> ${after}KiB;main 仍是 $(git -C "$dir" rev-list --count main) 个提交)"
}


# ──────────────────────────────────────────────────────────────────────────

banner "删库重建 + 更名:home-automation-configs -> scripts-hub"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "预检:备份、本地仓库、gh"
case "$(uname -s)" in
  MINGW*|MSYS*|CYGWIN*) : ;;
  *) warn "这套流程是为 Windows 本机写的;换机器跑请先确认路径与备份位置" ;;
esac
command -v gh >/dev/null 2>&1 || wsh_die "没装 gh CLI。" "装好并 gh auth login 再重跑。"
gh auth status >/dev/null 2>&1 || wsh_die "gh 未登录。" "先跑 gh auth login。"
wsh_ok "gh 已登录:$(gh api user --jq .login)"
say "home-automation-configs 要删库重建为 scripts-hub,删之前必须有可用的镜像备份;缺了就停下。"
say "备份按新名 scripts-hub-backup-*.git 查找,同时接受旧名 home-automation-configs-backup-*.git。"
check_backup "scripts-hub / home-automation-configs" HAC_BACKUP "${HAC_BACKUP_GLOBS[@]}"
[[ -d "$HAC_DIR/.git" ]] || wsh_die "找不到本地仓库:$HAC_DIR" "重建后要推的就是它,缺了先克隆一份。"
wsh_ok "旧名 $OLD_SLUG · 本地克隆在 $HAC_DIR($(git -C "$HAC_DIR" rev-list --count main) 个提交,工作区 $(git -C "$HAC_DIR" status --porcelain | wc -l) 处改动)"
[[ -f "$HAC_DIR/weread-signin/README.md" ]] || wsh_die "$HAC_DIR/weread-signin 里没有快照。" \
  "先跑 bash scripts/sync-weread-signin.sh 把 weread-signin 代码同步进来,再重跑本向导。"
wsh_ok "weread-signin 快照已就位($(git -C "$HAC_DIR" ls-files weread-signin | wc -l) 个已入库文件)"
[[ -d "$WEREAD_DIR/.git" ]] || warn "找不到本机开发克隆 $WEREAD_DIR,最后一步的只读校验会跳过"
pause "备份与本地仓库都就绪,按回车进入授权"

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "授权删除权限(用完可撤)"
say "删库要 delete_repo 权限;已经有权就跳过,没有则临时授权一次性扩一下。"
if gh_has_scope delete_repo; then
  wsh_ok "当前 token 已有 delete_repo,跳过授权"
else
  step "gh 会打开浏览器并显示一次性码;把码填进去,勾选 delete_repo,点授权。"
  step "授权完成后浏览器页面会显示成功,终端会自动继续。"
  warn "撤权:删完库按最小范围重登一次 —— gh auth login --hostname github.com --git-protocol https --web"
  pause "按回车开始授权(会打开浏览器)"
  gh auth refresh -h github.com -s delete_repo \
    || wsh_die "授权没完成,删除阶段会失败。" "重跑本脚本只会重做这一阶段。"
  gh_has_scope delete_repo \
    || wsh_die "授权后仍看不到 delete_repo scope。" \
         "确认授权时勾选了 delete_repo;企业策略禁止时可改用网页 Settings -> Danger Zone 手动删。"
  wsh_ok "delete_repo 已授予(gh auth refresh)"
fi

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "删除旧名 home-automation-configs"
say "force push 之后旧对象仍能按旧 SHA 取到,只有删库重建才会真正消失。"
say "本轮顺带更名:删掉旧名,再以 scripts-hub 重建为 PUBLIC —— 旧对象随旧库一起消失。"
say "weread-signin 已并入本仓库的 weread-signin/ 快照,不再有独立仓库要处理。"
step "先记下删除前的 ref 与备份里的旧提交,重建后逐个探测,确认取不回。"
capture_old_shas
step "再把旧仓库的 topics 抄下来,新仓库重建后照抄回去。"
capture_topics
warn "删除不可逆。备份是唯一的回滚依据:$HAC_BACKUP"
delete_repo "$OLD_SLUG" "$HAC_BACKUP"

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "以新名重建 scripts-hub 为 PUBLIC"
say "空库重建:一次提交都没有,历史从零开始;新仓库名 $NEW_SLUG。"
create_repo "$NEW_SLUG" "$HAC_DESC"
say "写回话题标签(用上一步从旧仓库抄下来的那一组,整组覆盖):"
load_topics
set_topics "$NEW_SLUG" "${HAC_TOPICS[@]}"
note "许可不用设:GitHub 从仓库里的 LICENSE 识别(根目录 GPL-3.0;weread-signin/ 自带 MIT)。"
pause "空库在、话题也回来了,按回车开始推送"

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "推送本地干净历史并校验"
say "本地克隆里已经是清洗后的历史:作者邮箱统一 zzz210s@qq.com、个人路径占位化、无凭据。"
say "推送目标改为新仓库 $NEW_SLUG,并把本地 origin 改指它(本地目录名仍叫 home-automation-configs)。"
say "再剪掉本地 pack 里重写前的旧对象(不会被 push,但留着迟早在别处漏出来):"
prune_local "$HAC_DIR"
publish_repo "$NEW_SLUG" "$HAC_DIR"
say "验证旧对象(删除前记下的那批 SHA 在新仓库里也应该一个都取不回;用一次性裸库探测,不碰本地克隆):"
check_no_old_objects "$NEW_SLUG" "$HAC_DIR" "$SHA_FILE"
say "最后确认删库重建没弄坏本机凭据:用现有 Key 跑一次只读统计(读官方数据,不上报、不改数据)。"
note "不重领 Key:Key 片段进过 git 历史,但仓库当时是私有的、旧 SHA 从未公开,故不轮换。"
note "weread-signin 没有 GitHub Actions workflow,这把 Key 不需要设成 repo secret。"
if [[ ! -f "$KEY_FILE" ]]; then
  warn "找不到 Key 文件 $KEY_FILE;跳过只读校验,需人工确认本机凭据还在。"
elif ( cd "$WEREAD_DIR" && node src/stats.js weekly ); then
  wsh_ok "读回官方统计成功,现有 Key 在删库重建后仍可用"
else
  warn "读统计失败:Key 可能失效或被清理。文件是 $KEY_FILE,本向导不重领,需人工处理。"
fi

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "收尾确认"
vis=$(gh api "repos/$NEW_SLUG" --jq .visibility 2>/dev/null || echo 读不到)
branch=$(gh api "repos/$NEW_SLUG" --jq .default_branch 2>/dev/null || echo 无)
commits=$(gh api "repos/$NEW_SLUG/commits?per_page=1" --jq length 2>/dev/null || echo 0)
if [[ "$vis" == "PUBLIC" && "$commits" != "0" ]]; then
  wsh_ok "$NEW_SLUG:$vis · 默认分支 $branch · 有新历史"
else
  wsh_bad "$NEW_SLUG:可见性 $vis、提交探测 $commits —— 需要人工看一眼"
fi
if gh api "repos/$OLD_SLUG" --jq .full_name >/dev/null 2>&1; then
  wsh_bad "旧名 $OLD_SLUG 仍然存在 —— 删除没生效,确认删的是同一个仓库"
else
  wsh_ok "旧名 $OLD_SLUG 已 404(不再存在)"
fi
wsh_ok "本地 $HAC_DIR 的 origin 已指向 https://github.com/$NEW_SLUG.git(目录名仍是 home-automation-configs)"
warn "可选的收尾:撤掉 delete_repo 权限 —— gh auth login --hostname github.com --git-protocol https --web"
note "本脚本留下的临时文件:$SHA_DIR/(删除前的 SHA 记录,验证完可删)"

finish
