#!/usr/bin/env bash
#
# wizard-public-reset:删库重建 + 更名 home-automation-configs -> scripts-hub。
#
# 为什么要删库:本仓库 force push 清洗过历史,旧对象仍能按旧 SHA 取到 —— 只有
# 删库重建才真正消失。本轮顺带更名:删掉 Zzz210s/home-automation-configs,
# 以新名 Zzz210s/scripts-hub 重建为 PUBLIC(旧对象随旧库一起消失),再把本地
# 干净历史推过去、origin 改指新地址。
# 本地目录名沿用 home-automation-configs(只改远程仓库名,免得带偏本机计划任务)。
# 备份镜像:优先新名 scripts-hub-backup-*.git,同时接受更名前的旧名
# home-automation-configs-backup-*.git —— 两种名字都算合格备份。
# weread-signin 已并入本仓库的 proj-weread-signin/ 快照,不再有独立仓库要处理。
#
# 不重领微信读书 API Key:Key 片段进过 git 历史,但仓库当时是私有的、旧 SHA 从未公开,
# 用户判断不必轮换。本向导只读取现有 Key,推送后用它跑一次只读校验。
#
# 用法:bash scripts/wizard-public-reset.sh
# 机器相关路径不写死:默认读 ~/.config/automation-suite/local-paths.env,也可用环境变量覆盖。
# 可随时 Ctrl-C;重跑会跳过已完成的部分(已删的仓库、已建的仓库、已推送的历史)。
# Generated by the /wizard skill.
#
# 顶部库段(输出/交互/值持久化/收尾汇总)已抽到 scripts/lib/*.sh,不要在这里另写一份;
# 本文件只保留流程编排与阶段跳转,阶段在下面 "STAGES" 标记之下。

set -euo pipefail

REPO_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
. "$REPO_DIR/scripts/lib/wizard-common.sh"
. "$REPO_DIR/scripts/lib/reset-common.sh"
. "$REPO_DIR/scripts/lib/reset-verify.sh"
. "$REPO_DIR/scripts/lib/reset-gh.sh"

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# ──────────────────────────────────────────────────────────────────────────

banner "删库重建 + 更名:home-automation-configs -> scripts-hub"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "预检:备份、本地仓库、gh"
case "$(uname -s)" in
  MINGW*|MSYS*|CYGWIN*) : ;;
  *) warn "这套流程是为 Windows 本机写的;换机器跑请先确认路径与备份位置" ;;
esac
command -v gh >/dev/null 2>&1 || wsh_die "没装 gh CLI。" "装好并 gh auth login 再重跑。"
gh auth status >/dev/null 2>&1 || wsh_die "gh 未登录。" "先跑 gh auth login。"
wsh_ok "gh 已登录:$(gh api user --jq .login)"
say "home-automation-configs 要删库重建为 scripts-hub,删之前必须有可用的镜像备份;缺了就停下。"
say "备份按新名 scripts-hub-backup-*.git 查找,同时接受旧名 home-automation-configs-backup-*.git。"
check_backup "scripts-hub / home-automation-configs" HAC_BACKUP "${HAC_BACKUP_GLOBS[@]}"
[[ -d "$HAC_DIR/.git" ]] || wsh_die "找不到本地仓库:$HAC_DIR" "重建后要推的就是它,缺了先克隆一份。"
wsh_ok "旧名 $OLD_SLUG · 本地克隆在 $HAC_DIR($(git -C "$HAC_DIR" rev-list --count main) 个提交,工作区 $(git -C "$HAC_DIR" status --porcelain | wc -l) 处改动)"
[[ -f "$HAC_DIR/proj-weread-signin/README.md" ]] || wsh_die "$HAC_DIR/proj-weread-signin 里没有快照。" \
  "先跑 bash scripts/sync-weread-signin.sh 把 proj-weread-signin 代码同步进来,再重跑本向导。"
wsh_ok "proj-weread-signin 快照已就位($(git -C "$HAC_DIR" ls-files proj-weread-signin | wc -l) 个已入库文件)"
[[ -d "$WEREAD_DIR/.git" ]] || warn "找不到本机开发克隆 $WEREAD_DIR,最后一步的只读校验会跳过"
pause "备份与本地仓库都就绪,按回车进入授权"

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "授权删除权限(用完可撤)"
say "删库要 delete_repo 权限;已经有权就跳过,没有则临时授权一次性扩一下。"
if gh_has_scope delete_repo; then
  wsh_ok "当前 token 已有 delete_repo,跳过授权"
else
  step "gh 会打开浏览器并显示一次性码;把码填进去,勾选 delete_repo,点授权。"
  step "授权完成后浏览器页面会显示成功,终端会自动继续。"
  warn "撤权:删完库按最小范围重登一次 —— gh auth login --hostname github.com --git-protocol https --web"
  pause "按回车开始授权(会打开浏览器)"
  gh auth refresh -h github.com -s delete_repo \
    || wsh_die "授权没完成,删除阶段会失败。" "重跑本脚本只会重做这一阶段。"
  gh_has_scope delete_repo \
    || wsh_die "授权后仍看不到 delete_repo scope。" \
         "确认授权时勾选了 delete_repo;企业策略禁止时可改用网页 Settings -> Danger Zone 手动删。"
  wsh_ok "delete_repo 已授予(gh auth refresh)"
fi

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "删除旧名 home-automation-configs"
say "force push 之后旧对象仍能按旧 SHA 取到,只有删库重建才会真正消失。"
say "本轮顺带更名:删掉旧名,再以 scripts-hub 重建为 PUBLIC —— 旧对象随旧库一起消失。"
say "weread-signin 已并入本仓库的 proj-weread-signin/ 快照,不再有独立仓库要处理。"
step "先记下删除前的 ref 与备份里的旧提交,重建后逐个探测,确认取不回。"
capture_old_shas
step "再把旧仓库的 topics 抄下来,新仓库重建后照抄回去。"
capture_topics
warn "删除不可逆。备份是唯一的回滚依据:$HAC_BACKUP"
delete_repo "$OLD_SLUG" "$HAC_BACKUP"

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "以新名重建 scripts-hub 为 PUBLIC"
say "空库重建:一次提交都没有,历史从零开始;新仓库名 $NEW_SLUG。"
create_repo "$NEW_SLUG" "$HAC_DESC"
say "写回话题标签(用上一步从旧仓库抄下来的那一组,整组覆盖):"
load_topics
set_topics "$NEW_SLUG" "${HAC_TOPICS[@]}"
note "许可不用设:GitHub 从仓库里的 LICENSE 识别(根目录 GPL-3.0;proj-weread-signin/ 自带 MIT)。"
pause "空库在、话题也回来了,按回车开始推送"

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "推送本地干净历史并校验"
say "本地克隆里已经是清洗后的历史:作者邮箱统一 zzz210s@qq.com、个人路径占位化、无凭据。"
say "推送目标改为新仓库 $NEW_SLUG,并把本地 origin 改指它(本地目录名仍叫 home-automation-configs)。"
say "再剪掉本地 pack 里重写前的旧对象(不会被 push,但留着迟早在别处漏出来):"
prune_local "$HAC_DIR"
publish_repo "$NEW_SLUG" "$HAC_DIR"
say "验证旧对象(删除前记下的那批 SHA 在新仓库里也应该一个都取不回;用一次性裸库探测,不碰本地克隆):"
check_no_old_objects "$NEW_SLUG" "$HAC_DIR" "$SHA_FILE"
say "最后确认删库重建没弄坏本机凭据:用现有 Key 跑一次只读统计(读官方数据,不上报、不改数据)。"
note "不重领 Key:Key 片段进过 git 历史,但仓库当时是私有的、旧 SHA 从未公开,故不轮换。"
note "proj-weread-signin 没有 GitHub Actions workflow,这把 Key 不需要设成 repo secret。"
if [[ ! -f "$KEY_FILE" ]]; then
  warn "找不到 Key 文件 $KEY_FILE;跳过只读校验,需人工确认本机凭据还在。"
elif ( cd "$WEREAD_DIR" && node src/stats.js weekly ); then
  wsh_ok "读回官方统计成功,现有 Key 在删库重建后仍可用"
else
  warn "读统计失败:Key 可能失效或被清理。文件是 $KEY_FILE,本向导不重领,需人工处理。"
fi

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "收尾确认"
vis=$(gh api "repos/$NEW_SLUG" --jq .visibility 2>/dev/null || echo 读不到)
branch=$(gh api "repos/$NEW_SLUG" --jq .default_branch 2>/dev/null || echo 无)
commits=$(gh api "repos/$NEW_SLUG/commits?per_page=1" --jq length 2>/dev/null || echo 0)
if [[ "$vis" == "PUBLIC" && "$commits" != "0" ]]; then
  wsh_ok "$NEW_SLUG:$vis · 默认分支 $branch · 有新历史"
else
  wsh_bad "$NEW_SLUG:可见性 $vis、提交探测 $commits —— 需要人工看一眼"
fi
if gh api "repos/$OLD_SLUG" --jq .full_name >/dev/null 2>&1; then
  wsh_bad "旧名 $OLD_SLUG 仍然存在 —— 删除没生效,确认删的是同一个仓库"
else
  wsh_ok "旧名 $OLD_SLUG 已 404(不再存在)"
fi
wsh_ok "本地 $HAC_DIR 的 origin 已指向 https://github.com/$NEW_SLUG.git(目录名仍是 home-automation-configs)"
warn "可选的收尾:撤掉 delete_repo 权限 —— gh auth login --hostname github.com --git-protocol https --web"
note "本脚本留下的临时文件:$SHA_DIR/(删除前的 SHA 记录,验证完可删)"

finish
