#!/usr/bin/env bash
#
# wizard-oracle:开通 Oracle Cloud Always Free ARM 主机(Ubuntu 24.04)
# 一步步带你注册、建实例、放行两处防火墙、写 ~/.ssh/config 并验证连通。
# 用法:bash scripts/wizard-oracle.sh
# 值写到 ~/.config/automation-suite/vm.env;可随时 Ctrl-C,重跑会记住已存的值。
# Generated by the /wizard skill.
#
# 顶部库段(输出/交互/值持久化/收尾汇总)已抽到 scripts/lib/wizard-common.sh,不要在这里
# 另写一份;本文件只保留流程编排与阶段跳转,阶段在下面 "STAGES" 标记之下。

set -euo pipefail

REPO_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
. "$REPO_DIR/scripts/lib/wizard-common.sh"

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=4

# 值持久化到 ~/.config/automation-suite/vm.env(不是仓库内的 .env)
ENV_FILE="$HOME/.config/automation-suite/vm.env"
mkdir -p "$(dirname "$ENV_FILE")"

banner "Oracle Cloud 免费 ARM 主机开通"

# ── Stage 1: 注册 Oracle Cloud ────────────────────────────────────────────
stage "注册 Oracle Cloud 账号"
say "先开一个 Oracle Cloud 账号;后面那台永久免费的 ARM 主机就挂在它下面。"
open_url "https://signup.cloud.oracle.com/"
step "用邮箱注册,国家/地区与姓名要与支付方式一致,否则后面的验证容易被拒。"
step "验证邮箱,再验证手机号(收短信验证码)。"
step "填一张银行卡做身份验证:Always Free 资源不扣费,只是验卡(部分地区会先扣约 1 美元再退回)。"
step "选 Home Region:优先 ap-tokyo-1(东京)或 ap-singapore-1(新加坡),离得近、延迟低。"
warn "Home Region 建号后不能改。ARM 实例常有「容量不足」,选热门区域时可能需要换可用域(AD)重试。"
pause "账号注册好、能登进控制台后按回车继续"

# ── Stage 2: 创建 ARM 实例 ────────────────────────────────────────────────
stage "创建 ARM 实例(Ubuntu 24.04)"
say "在控制台创建一台 Always Free 的 ARM 实例。界面措辞以控制台实际界面为准。"
open_url "https://cloud.oracle.com/"
step "左上角菜单:Compute -> Instances -> Create instance。"
step "Image and shape -> Change image -> 选 Canonical Ubuntu 24.04。"
step "Change shape -> Ampere -> VM.Standard.A1.Flex,先给 2 OCPU / 12 GB(Always Free 上限 4 OCPU / 24 GB,不够再加)。"
step "Add SSH keys -> Paste public keys,粘贴本机公钥 ~/.ssh/id_ed25519.pub 的内容。"
note "没有这个公钥就先在本机生成:ssh-keygen -t ed25519(一路回车,用默认路径)。公钥可以公开,私钥绝不外传。"
step "Networking 保持默认(会新建/选用一个 VCN 与公网子网,给实例分配公网 IP)。"
step "Create 后等状态变成 Running,在实例详情页复制 Public IP address(公网 IP)。"
ask ORACLE_VM_IP "粘贴这台实例的公网 IP:"
write_env ORACLE_VM_IP "$ORACLE_VM_IP"
say "登录用户名固定是 ubuntu(不是 root),后面连接都用它。"
pause "记好 IP 与用户名后按回车继续"

# ── Stage 3: 开放网络(两处) ──────────────────────────────────────────────
stage "开放网络(两处都要放行)"
say "Oracle 有两个互相独立的地方会挡 SSH,只放一处仍会连接超时。"
step "第一处(控制台):VCN -> Security Lists -> Default Security List -> Add Ingress Rules。"
note "Source CIDR 填 0.0.0.0/0(或只填你自己的出口 IP/32,更安全);IP Protocol 选 TCP;Destination Port Range 填 22。"
step "第二处(实例内 iptables):新版 Ubuntu 镜像自带的 iptables 规则会挡 22,要在实例里放行。"
say "在本机终端 SSH 进这台实例(IP 换成上面记的,私钥路径按实际填):"
note "ssh -i ~/.ssh/id_ed25519 ubuntu@<公网IP>"
say "登进去后执行这两条,再退出:"
note "sudo iptables -I INPUT 6 -p tcp --dport 22 -j ACCEPT"
note "sudo netfilter-persistent save"
warn "第二处必须在实例内执行。若这时完全连不上,先用控制台的 Serial Console 登进去执行同样两条命令(以控制台实际界面为准)。"
pause "两处都放行、能正常登录后按回车继续"

# ── Stage 4: 收集连接信息并验证 ───────────────────────────────────────────
stage "收集连接信息并验证"
say "把连接信息写进 ~/.ssh/config,以后用 oracle-vm 这个名字就能连。"
note "这里只要私钥的文件路径,不会读取也不会回显私钥内容。"
ask ORACLE_VM_IP "公网 IP:"
ORACLE_VM_IP="${ORACLE_VM_IP:-}"
ask ORACLE_VM_USER "登录用户名:"
ORACLE_VM_USER="${ORACLE_VM_USER:-ubuntu}"
ask ORACLE_VM_SSH_KEY "私钥路径:"
ORACLE_VM_SSH_KEY="${ORACLE_VM_SSH_KEY:-$HOME/.ssh/id_ed25519}"
write_env ORACLE_VM_IP "$ORACLE_VM_IP"
write_env ORACLE_VM_USER "$ORACLE_VM_USER"
write_env ORACLE_VM_SSH_KEY "$ORACLE_VM_SSH_KEY"

KEY_PATH="${ORACLE_VM_SSH_KEY/#\~/$HOME}"
if [[ ! -f "$KEY_PATH" ]]; then
  warn "找不到私钥文件 $KEY_PATH;先在本机生成或改成正确的路径,再重跑本脚本。"
else
  perms=$(stat -c %a "$KEY_PATH" 2>/dev/null || stat -f %Lp "$KEY_PATH" 2>/dev/null || echo "")
  [[ -n "$perms" && "$perms" != "600" ]] && warn "私钥权限是 $perms,建议 chmod 600 $KEY_PATH(ssh 会拒绝权限过宽的私钥)。"
fi

SSH_DIR="$HOME/.ssh"
SSH_CONFIG="$SSH_DIR/config"
BEGIN_MARK="# >>> automation-suite oracle-vm >>>"
END_MARK="# <<< automation-suite oracle-vm <<<"

if confirm "把 oracle-vm 别名写进 $SSH_CONFIG?(已有同名的块会被替换)"; then
  mkdir -p "$SSH_DIR"
  chmod 700 "$SSH_DIR" 2>/dev/null || true
  touch "$SSH_CONFIG"
  chmod 600 "$SSH_CONFIG" 2>/dev/null || true
  tmp=$(mktemp)
  awk -v s="$BEGIN_MARK" -v e="$END_MARK" '$0==s{skip=1;next} $0==e{skip=0;next} !skip{print}' "$SSH_CONFIG" > "$tmp"
  {
    printf '%s\n' "$BEGIN_MARK"
    printf 'Host oracle-vm\n'
    printf '    HostName %s\n' "$ORACLE_VM_IP"
    printf '    User %s\n' "$ORACLE_VM_USER"
    printf '    IdentityFile %s\n' "$ORACLE_VM_SSH_KEY"
    printf '    IdentitiesOnly yes\n'
    printf '    ServerAliveInterval 30\n'
    printf '%s\n' "$END_MARK"
  } >> "$tmp"
  mv "$tmp" "$SSH_CONFIG"
  printf '  %s✓ wrote%s Host oracle-vm -> %s\n' "$GREEN" "$RESET" "$SSH_CONFIG"
fi

say "验证连通性..."
if ssh -o BatchMode=yes -o ConnectTimeout=10 -o StrictHostKeyChecking=accept-new oracle-vm 'echo ok && uname -a'; then
  printf '  %s✓ 连接成功%s\n' "$GREEN" "$RESET"
  step "接下来:把代码与凭据部署到主机,再装 systemd timer(见仓库 README 与 docs/scheduling-convention.md)。"
else
  warn "SSH 没连上,按顺序排查:"
  note "1) 控制台 Security List 是否放行了 TCP 22"
  note "2) 实例内是否执行了 iptables 那两条(--dport 22 放行)"
  note "3) 私钥权限是否是 600,用户名是否是 ubuntu"
  note "4) 公网 IP 是否变化(重启实例可能变),或实例状态不是 Running"
  pause "排查后按回车,脚本会再试一次(也可记下问题,重跑本脚本只重做这一阶段)"
  ssh -o BatchMode=yes -o ConnectTimeout=10 oracle-vm 'echo ok && uname -a' || warn "仍未连通;信息已写入 $ENV_FILE,可稍后重跑本脚本"
fi

finish
